### PR TITLE
Adding Clone replace and import preview endpoints.

### PR DESCRIPTION
**Pull request by prashanthlgowda**
Adding Clone and replace endpoint for SEP export

### CODE REVIEW

**Review by muqeethkowkab — APPROVED** [review]

**Review by muqeethkowkab — APPROVED** [review]
Changes Looks good.

**Review by muqeethkowkab — APPROVED** [review]
Changes Looks Good.

**Comment by michaelsteven** [comment]
Throughout, add javadoc and remove commented out annotations.

**Comment by prashanthlgowda** [comment]
Added javadocs and removed dead annotations.

**Review by muqeethkowkab — APPROVED** [review]
Changes Looks Good.

**Pull request merged**
